### ISSUE TITLE
protocol is always https

### ISSUE THREAD

**Issue by n4uti** [Werkspot/sitemap-bundle#3]
Just noticed that a single url in a sitemap always starts with https.

`<loc>{{ url.loc|replace({'http:': 'https:'}) }}</loc>`

It would be a better way to automatically detect if https is supported or not.

Beside this issue I think you should list how to register a SitemapProvider as service like this in the wiki:

```
    app.static.sitemap:
        class: AppBundle\Sitemap\StaticPageSitemapProvider
        arguments: ["@router.default"]
        tags:
            - { name: werkspot.sitemap_provider }

    #dynamic provider for loading some entities from a doctrine repository
    app.services.sitemap:
        class: AppBundle\Sitemap\ServicesSitemapProvider
        arguments: ["@router.default", "@doctrine"]
        tags:
            - { name: werkspot.sitemap_provider }
```

Thanks for this cool bundle!
